# Generated by Django 6.1 on 2026-09-07 13:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='kategoriya_ati')),
                ('order_index', models.IntegerField(verbose_name='kategoriya_indeksi')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ingidient_ati')),
                ('unit', models.CharField(max_length=50, verbose_name='ingridient_olshemi')),
                ('current_stock', models.IntegerField(verbose_name='skladtagi_qaldiq')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='restoran_ati')),
                ('address', models.CharField(max_length=100, verbose_name='restoran_adresi')),
                ('phone', models.CharField(max_length=12, verbose_name='restoran_tel_nomeri')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/', verbose_name='restoran_logosi')),
                ('is_active', models.BooleanField(default=True, verbose_name='restoran_statusi')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=12, verbose_name='user_tel_nomeri')),
                ('role', models.CharField(max_length=20, verbose_name='user_roli')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='restaurant.restaurant', verbose_name='restoran')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='klient')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='zakaz_ati')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='zakaz_ati')),
                ('price', models.IntegerField(verbose_name='zakaz_bahasi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dishes/logos/', verbose_name='zakaz_logosu')),
                ('is_available', models.BooleanField(default=True, verbose_name='zakaz_bar_elenligi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurant.category', verbose_name='categoriya')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='restaurant.restaurant', verbose_name='restoran')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='zakaz_statusi')),
                ('payment_method', models.CharField(max_length=20, verbose_name='tolem_turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='jaratilgan_waqti')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='jawilgan_waqti')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='restaurant.client', verbose_name='klient')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='ofitsiant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='zakazga_itemga_qosimsha')),
                ('status', models.CharField(max_length=50, verbose_name='zakaz_item_statusi')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='restaurant.dish', verbose_name='zakaz_haqqinda')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='restaurant.order', verbose_name='zakaz_haqqinda')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_serving', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeitem', to='restaurant.dish', verbose_name='maxsulat')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeitem', to='restaurant.ingredient', verbose_name='maxsulat')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='restaurant.restaurant', verbose_name='restoran'),
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurant.restaurant', verbose_name='restoran'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kirim', 'Kirim'), ('shigim', 'Shigim')], max_length=20, verbose_name='tranzaksiya_turi')),
                ('quantity', models.IntegerField(verbose_name='mugdari')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='sebebi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='tranzaksiya_waqti')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='restaurant.ingredient', verbose_name='ingridient')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('seats_count', models.IntegerField()),
                ('status_is_free', models.BooleanField(verbose_name='stol_statusi')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='restaurant.restaurant', verbose_name='restoran')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='rezerv_waqti')),
                ('guests_count', models.IntegerField()),
                ('status', models.CharField(max_length=50, verbose_name='rezerv_statusi')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='restaurant.client', verbose_name='rezerv qilgan klient')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='restaurant.restaurant', verbose_name='rezerv qilgan klient')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='restaurant.table', verbose_name='rezerv qilgan klient')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='restaurant.table', verbose_name='stol'),
        ),
    ]
