# Generated by Django 6.1 on 2026-09-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order_index',
            field=models.CharField(max_length=50, unique=True, verbose_name='kategoriya_indeksi'),
        ),
    ]
