# Generated by Django 6.1 on 2026-09-11 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='klient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/logos/', verbose_name='zakaz_logosi'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.IntegerField(verbose_name='awqat/ishimlik bahasi'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurant.restaurant', verbose_name='restoran'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='restaurant.dish', verbose_name='awqat/ishimlik'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='restaurant.order', verbose_name='zakaz'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='restaurant.restaurant', verbose_name='rezerv qilingan restoran'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='restaurant.table', verbose_name='rezerv qilingan stol'),
        ),
    ]
