# Generated by Django 6.1 on 2026-09-25 06:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_order_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingridient', 'verbose_name_plural': 'Ingridientler'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ingidient_ati'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.restaurant', verbose_name='restoran'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Porciya sani 1 den kem bolmawi kerek')]),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='restaurant.dish', verbose_name='dish'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='restaurant.ingredient', verbose_name='maxsulat'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='restaurant.client', verbose_name='rezerv qilgan klient'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'restaurant')},
        ),
    ]
